### ISSUE TITLE
Improve path smoothing in the free hand tool

### ISSUE THREAD

**Issue by nasseralkmim** [misohena/el-easydraw#17]
Hi,

Do you use the freehand tool with a tablet? I noticed that the smoothing capabilities distort the lines that I draw with the Wacom tablet, especially letters.

Is this something that can be easily improved?

Best regards,

**Comment by misohena** [comment]
Hello,

I don't use a tablet, but I sometimes notice that lines appear distorted when using a mouse.

A while ago, I added a mechanism to significantly reduce the number of points generated, but this may be causing the side effect.

In commit 862994c1e715109d1c5fe436a39a31e989dce4cd, I added an option to enable the previous behavior.

Setting (setq edraw-editor-tool-freehand-smoothing-method 'each-point) will enable the previous behavior. Additionally, setting (setq edraw-editor-tool-freehand-smoothing-method nil) will completely disable smoothing.

I think it would take some time to make improvements to the current method.

(Original Message)
こんにちは。

私はタブレットは使用していませんが、マウスで線が歪むと感じることはあります。

少し前に生成する点の数を大幅に削減する仕組みを追加しましたが、その副作用かもしれません。

コミット862994c1e715109d1c5fe436a39a31e989dce4cdで以前の挙動に戻すオプションを追加しました。

(setq edraw-editor-tool-freehand-smoothing-method 'each-point)とすると以前の挙動になります。また、(setq edraw-editor-tool-freehand-smoothing-method nil)とすると完全にスムーズ化が行われなくなります。

現在の方式を改善するには多くの時間が必要になると思います。

**Comment by nasseralkmim** [comment]
Hi, The no-smoothing option is a good idea. Thanks
