### ISSUE TITLE
emacs29 on linux and mac don't work

### ISSUE THREAD

**Issue by wn** [misohena/el-easydraw#19]
<img width="677" alt="image" src="https://github.com/misohena/el-easydraw/assets/25412108/f553ff0f-b17e-41b1-97ac-bffd4b1d7625">

I'm having the error editor already exist, but I don't see the editor anywhere. I believe this issue only happens after upgrading to emac29.

**Comment by misohena** [comment]
(Translated Message)
Hello wm.

I'm currently developing with Emacs29.1 and couldn't reproduce the problem. Tested on MS-Windows (Official Build) and Ubuntu22 (Snap Store). The version of Org-mode used was 9.6.11 (latest version of ELPA) or 9.6.6 (included with Emacs 29.1).

The error appears the second time you try to open the editor, right? The first time, there was no reaction. If so, there is a high possibility that the editor overlay is not displayed for some reason.

Maybe some other package you're using is interfering with it.

I hope there is some clue.

(Original Message)
wmさんこんにちは。

私は現在Emacs29.1で開発していますが、その問題は再現できませんでした。MS-Windows(Official Build)とUbuntu22(Snap Store)でテストしました。使用したOrg-modeのバージョンは9.6.11(ELPAの最新版)または9.6.6(Emacs29.1付属)です。

そのエラーは二度目にエディタを開こうとしたときに出るということですよね？　一度目は何も反応が無くて。であれば何らかの原因でエディタのオーバーレイが表示されていない可能性が高いでしょう。

何か他に使っているパッケージが干渉しているのかもしれません。

何か手がかりがあると良いのですが。

**Comment by wn** [comment]
I think the issue is that I start emacs in `emacs -nw` (i.e. in terminal mode). Running `emacs` and opening edraw in the dedicated emacs window doesn't produce the issue. 

Thank you.
