### ISSUE TITLE
edraw context menu interferes with context-menu-mode

### ISSUE THREAD

**Issue by TobiasZawada** [misohena/el-easydraw#21]
The Edraw-editor context menu interferes with `context-menu-mode`.

Reconstruction:

- Activate `context-menu-mode`. This is a global minor mode.
- Open any org-file with a valid edraw-link and start the edraw-editor for that image.
- Left-click on any object in the image opens first the context menu of `context-menu-mode` and not that one of the edraw-editor.

**Comment by misohena** [comment]
(Translated Message)
Hello Tobias Zawada. Thank you for your report.

I was able to reproduce the problem.

I've probably never used context-menu-mode, but this looks good.

I looked into the mechanism of context-menu-mode, and found that the command for the down-mouse-3 event is assigned to the keymap of the minor mode context-menu-mode, and the context menu is opened from that command.

In that case, it seemed like the problem could be avoided by adding down-mouse-3 to the keymap of the edraw editor, so I tried fixing it in commit c7a77f4. What do you think?

Also, Org's inline images, property editor, and shape picker also use mouse-3, so I fixed them.

(Original Message)
TobiasZawadaさんこんにちは。ご報告ありがとうございます。

問題を再現できました。

context-menu-modeはおそらく使ったことはありませんでしたが、これは良さそうですね。

context-menu-modeの仕組みを調べてみましたが、マイナーモードcontext-menu-modeのキーマップにdown-mouse-3イベントに対するコマンドが割り当てられており、そのコマンドからコンテキストメニューを開いているのですね。

そうなると、edrawエディタのキーマップにdown-mouse-3を追加することでも問題を回避できそうでしたのでコミットc7a77f4で修正してみましたがいかがでしょうか。

また、Org-modeのインライン画像やプロパティエディタ、シェイプピッカーもmouse-3を使用するので修正しました。

**Comment by TobiasZawada** [comment]
I am currently using `edraw-edit-svg` in the context of `adoc-mode` and not in the context of `org-mode`.
So [!22](https://github.com/misohena/el-easydraw/pull/22) seemed to be a good solution.
It restricts the deactivation of the context menu to the area of the overlay.

I am not sure whether you can reach the same effect when you change the keymaps of minor-modes.

But, I will try your fix when I have time. Hopefully, this night.

**Comment by TobiasZawada** [comment]
I tested your commit https://github.com/misohena/el-easydraw/commit/c7a77f416a997343cb4cee483a7c0baeb9dbf590 and it looks like it also solves the problem.
