### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by SockPastaRock** [misohena/el-easydraw#27]
Hi. I love your project but I seem to be having a memory leak issue when I edit images. After a brief time of drawing an image with stable memory consumption, suddenly emacs will rapidly begin to consume all of my RAM until my PC freezes. This only happens when I edit an image with edraw.

I am not sure how to investigate the root cause in any real depth to assist you in resolving it. It is also difficult to investigate because my PC completely freezes very quickly after it begins to consume RAM. If there is anything I can do to give you more information please let me know.

**Comment by misohena** [comment]
Hello @SockPastaRock.

Could you please tell me your environment?

I've been wondering about memory leaks for a long time. However, in my environment (mainly Windows 10 & Emacs 27 and later), it doesn't freeze. I tried to check the memory consumption in the task manager, and it was repeating the following situation:

Before opening the edraw link: 71MB => After opening: 86MB => During editing: It continued to increase and dropped to about 130MB after exceeding 220MB

When I run M-: (clear-image-cache), the memory usage is greatly reduced, so I strongly suspect that the image cache is related. Perhaps the image for each frame is cached.

I'll try to clear the cache of old images every time a frame is updated later.

However, if Emacs freezes, it may be necessary to report it as an Emacs bug. There are few Emacs applications that generate a large number of images like this, so there may be some hidden problem.

**Comment by misohena** [comment]
(Translated Message)
In commit fa63f5d, I set image-flush to be used when updating images, and the large fluctuations in memory usage have disappeared in my environment. Please try it.

Also, according to the manual ( https://www.gnu.org/software/emacs/manual/html_node/elisp/Image-Cache.html#index-image_002dcache_002deviction_002ddelay ), if the variable image-cache-eviction-delay is nil , Emacs will not clear the cache. Please check just to be sure.

By the way, I think that other problems related to the image cache (changes to external images referenced by the image element sometimes not reflected) were also fixed at the same time.

(Original Message)
コミットfa63f5dで画像更新時にimage-flushするようにしたところ、私の環境ではメモリ使用量の大きな変動は起こらなくなりました。試してみてください。

また、マニュアル( https://www.gnu.org/software/emacs/manual/html_node/elisp/Image-Cache.html#index-image_002dcache_002deviction_002ddelay )によれば image-cache-eviction-delay という変数が nil のとき、Emacsはキャッシュをクリアしないらしいです。念のためご確認頂ければと。

ちなみに、画像キャッシュにまつわる他の不具合(image要素で参照している外部画像の変更が反映されないことがある)も同時に直ったと思います。

**Comment by misohena** [comment]
(Translated Message)
Additionally fixed a95de40 and 6f93e74.

(Original Message)
追加で a95de40 と 6f93e74 を修正しました。

**Comment by misohena** [comment]
状況が分からないので閉じます。

**Comment by SockPastaRock** [comment]
(translated)
私の応答が遅くてすみません。更新されたリリースを今日テストしたところ、メモリリークの問題が修正されたようです。ありがとうございました

(original)
Sorry for my slow response. Upon testing your updated release today, it appears that the memory leak issue is now fixed. Thank you very much
