### ISSUE TITLE
Colour panel not showing on Ubuntu pgtk native comp Emacs

### ISSUE THREAD

**Issue by markgdawson** [misohena/el-easydraw#4]
On my machine:

Ubuntu 20.04.3
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
Pure GTK build with native compilation

The colour does not show on the left panel.
![el-easydraw](https://user-images.githubusercontent.com/16015869/135398155-f47008c6-3884-43ce-9ea4-28d82a2031d7.png)

**Comment by misohena** [comment]
markgdawsonさんこんにちは。
ご報告ありがとうございます。

とても不思議な現象ですね。一番右のバーも正しく表示されていません。共通点はアルファチャネルを含んだグラデーションを使っているという点でかもしれません。

SVGの描画はおそらくlibrsvgとCairoによって行われていると思うのでそれらに問題があるか、または、edraw-color-picker.elが問題のあるSVGを生成しているのかもしれません。

同じ環境でEmacs27では動作しますか？

Google Translate:

Hello markgdawson.
Thank you for your report.

It's a very strange phenomenon. The rightmost bar is also not displayed correctly. What they have in common may be that they use a gradient that includes an alpha channel.

I think the SVG drawing is probably done by librsvg and Cairo, so there may be problems with them, or edraw-color-picker.el may be generating the problematic SVG.

Will it work with Emacs 27 in the same environment?

**Comment by misohena** [comment]
Try displaying this SVG in image-mode.

`<svg width="200" height="200" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <defs>
      <linearGradient id="Gradient1">
        <stop offset="0%" stop-color="rgba(255,0,0,1)" />
        <stop offset="100%" stop-color="rgba(255,0,0,0)" />
      </linearGradient>
  </defs>
  <rect x="0" y="0" width="200" height="200" fill="url(#Gradient1)"/>
</svg>
`

I tried it in my environment. From the left, Emacs27.2 official build, Emacs26.3 original build, and Emacs26.3 official build (all for Windows).

![gradient-test](https://user-images.githubusercontent.com/250549/135614655-5561f2b2-f731-4a23-b163-43dc7d352ff6.png)
