### ISSUE TITLE
Cannot save edits from blank image

### ISSUE THREAD

**Issue by nxtruong** [misohena/el-easydraw#7]
After your most recent commit https://github.com/misohena/el-easydraw/commit/4d0dc9e5f67e515000664cc2bf67fc9d0628e211 to fix issue #5, I can no longer save edits starting from a blank image. When I type `[[edraw::]]` and then `C-c C-o` to open the editor, draw something, then `C-c C-c` to save it (or use the menu to finish edit), I receive an error message "Failed to save. Wrong type argument: arrayp, nil. Discard changes?(yes or no)". If I choose NO then it goes back to editing, and if I choose YES then nothing is saved (empty). However, if I copy data from an existing valid SVG image to start from a non-blank image, then it works, my new edits can be saved.

**Comment by misohena** [comment]
空のリンクから編集を開始すると保存できないとのことですが、私では問題を再現できませんでした。

4d0dc9e5f67e515000664cc2bf67fc9d0628e211 は編集には関係ないので、その一つ前の d94a656c51c357b8b68b12356eb68f8ef47c175a が原因かもしれません。ただ、このコミットは関数を分割しただけで動作は変えていないと思います。それとも我々がまだ見つけていない不具合が表面化したのかもしれません。

セーブ時の関数呼び出しは edraw-org-link-finish-edit => edraw-save => edraw-org-link-save-svg という流れになっています。そこから問題の発生箇所を追えると思います。

I couldn't reproduce the problem.

4d0dc9e5f67e515000664cc2bf67fc9d0628e211 is not relevant for editing, so the previous d94a656c51c357b8b68b12356eb68f8ef47c175a may be the cause. However, I don't think this commit has changed the behavior just by splitting the function. Or maybe a bug we haven't found yet has surfaced.

The function call at the time of saving is in the flow of edraw-org-link-finish-edit => edraw-save => edraw-org-link-save-svg. From there, you can track down where the problem occurred.

**Comment by nxtruong** [comment]
OK, I figured out the problem. It's actually my mistake. I typed two colons in `[[edraw::]]` instead of one colon, which, I guess, resulted in an empty array for the data (the error message). The issue can be closed.

**Comment by misohena** [comment]
おー、確かにあなたは[[edraw::]]と書いていました。私もそれを見落としていました！

何かもっと分かりやすいエラーが出ると良いのでしょうね。例えば C-c C-o を押したときにパースエラーを表示するとか。考えてみます。ご報告ありがとうございました。

追伸。テスト中にファイルリンクの最初の編集後に画像がインライン表示されない不具合を見つけました。これも直そうと思います。

Oh, surely you wrote [[edraw ::]]. I overlooked it too!

It would be nice to get some more straightforward error. For example, when you press C-c C-o, a parsing error is displayed. I'll think about it. Thank you for your report.

PS. During testing I found a bug where the image was not displayed inline after the first edit of the file link. I will fix this as well.
