### ISSUE TITLE
Click position offset

### ISSUE THREAD

**Issue by markgdawson** [misohena/el-easydraw#8]
The click position seems to be interpreted as slightly to the right of the position of point.

I need to click further just to the left of any buttons or controls to use them. Also, when I click on the panel on the left hand side, the circle denoting the colour is offset to the right of the mouse.

It looks to me as if all the mouse clicks are interpreted as being slightly offset.

**Comment by misohena** [comment]
状況がよく分からず返答も無いのでクローズします。

Emacsにはマウス座標がずれるバグがいくつか見つかっています。気になるようならEmacsにバグ報告して下さい。

(Google Translate):
I don't understand the situation well and there is no reply, so I will close it.

Some bugs have been found in Emacs that cause mouse coordinates to shift. Please report bugs to Emacs if you are concerned.
